### ISSUE TITLE
DEMO 运行在ios 9.0手机上，点击返回按钮奔溃了

### ISSUE THREAD

**Issue by zengjinzong** [SmileZXLee/ZXEmptyView#1]
<img width="1280" alt="屏幕快照 2019-10-10 上午11 37 16" src="https://user-images.githubusercontent.com/13520124/66537321-93bd1980-eb52-11e9-83f7-01ed9b056312.png">

**Comment by SmileZXLee** [comment]
感谢反馈，这个问题是由于遗漏了removeObserver导致的，最新版本(pod 1.0.4)已修复这个问题。
