### ISSUE TITLE
内存泄漏 DemoEmptyView，ZXEmptyContentView 没有释放

### ISSUE THREAD

**Issue by zengjinzong** [SmileZXLee/ZXEmptyView#2]
点击demo中返回按钮，DemoEmptyView，ZXEmptyContentView中存在内存没有释放的情况。

**Comment by SmileZXLee** [comment]
ZXEmptyContentView没有被释放是由于demo中【DemoTableViewVC】控制器因为循环引用未被释放导致的，有个地方遗漏了weakSelf，现已修复，感谢您的细心和反馈。
