### ISSUE TITLE
zx_startLoading并没有起到作用

### ISSUE THREAD

**Issue by jianjianhao** [SmileZXLee/ZXEmptyView#3]

**Comment by SmileZXLee** [comment]
您好！进过测试`-zx_startLoading`方法没有问题，您可以根据以下几点排查原因或提供一下demo或代码片段。  

* `-zx_startLoading `的作用是告诉ZXEmptyView请求开始，ZXEmptyView会自动隐藏emptyView，而非显示emptyView。
* 如果您将ZXEmptyView添加至tableView，则需要调用此tableView的`-zx_startLoading`方法才可生效。  

感谢您的反馈，如果有其他问题或更详尽的错误信息欢迎随时沟通以便我修正。

**Comment by jianjianhao** [comment]
非常抱歉，国庆期间没留意GitHub的消息，https://github.com/jianjianhao/ZXEmptyViewDemo.git，demo已经提供，情况是使用tableview在网络请求的时候调用zx_startLoading，空白页是先显示在隐藏的，模拟器使用了iOS14和iOS13.5 ，xcode12

**Comment by SmileZXLee** [comment]
> 非常抱歉，国庆期间没留意GitHub的消息，https://github.com/jianjianhao/ZXEmptyViewDemo.git，demo已经提供，情况是使用tableview在网络请求的时候调用zx_startLoading，空白页是先显示在隐藏的，模拟器使用了iOS14和iOS13.5 ，xcode12

您好，感谢您提供的demo。
您在Test1VC中控制器加载的时候书写了以下代码
```objc
[self.tableView zx_startLoading];
[self.tableView zx_setEmptyView:[DemoEmptyView class]];
```
您需要在ZXEmptyView初始化之后调用`-zx_startLoading`才可以生效，因此您需要修改为
```objc
[self.tableView zx_setEmptyView:[DemoEmptyView class]];
[self.tableView zx_startLoading];
```
即可。

**Comment by jianjianhao** [comment]
还是不行
<img width="980" alt="81FEFFFF-33ED-4798-8D22-DD09628050C1" src="https://user-images.githubusercontent.com/12797357/95544620-3b06b200-0a2e-11eb-9693-688ac7c6050f.png">
还是会先显示空白页再隐藏的

**Comment by SmileZXLee** [comment]
> 还是不行
> <img alt="81FEFFFF-33ED-4798-8D22-DD09628050C1" width="980" src="https://user-images.githubusercontent.com/12797357/95544620-3b06b200-0a2e-11eb-9693-688ac7c6050f.png">
> 还是会先显示空白页再隐藏的

感谢您的反馈和协助，经测试是由于首次加载时，系统会自动调用`-reloadData`导致的，此问题已修复，您可以使用pod将`ZXEmptyView`更新至1.0.8即可。

**Comment by jianjianhao** [comment]
嗯已经可以了谢谢

**Comment by SmileZXLee** [comment]
> 嗯已经可以了谢谢

不客气，很抱歉影响您的正常使用了。您在使用过程中有任何建议和意见都可以随时联系我。
