### ISSUE TITLE
在使用WMPageController 或者 JXCategoryView，zx_startLoading会有先显示在隐藏的问题

### ISSUE THREAD

**Issue by jianjianhao** [SmileZXLee/ZXEmptyView#4]
我最近项目遇到使用WMPageController和JXCategoryView，里面嵌套tableview的时候调用zx_startLoading会有先显示在隐藏的bug
https://github.com/jianjianhao/ZXEmptyViewDemo.git
已经写了一个demo，作者有空看看

**Comment by SmileZXLee** [comment]
> 我最近项目遇到使用WMPageController和JXCategoryView，里面嵌套tableview的时候调用zx_startLoading会有先显示在隐藏的bug
> https://github.com/jianjianhao/ZXEmptyViewDemo.git
> 已经写了一个demo，作者有空看看

感谢您的反馈和协助！！新版本1.1.0已修复此问题，您可以更新一下。
