### ISSUE TITLE
手动导入报错

### ISSUE THREAD

**Issue by yuyunzhang** [SmileZXLee/ZXEmptyView#5]
[UITextField _stopScrollingAndZoomingAnimationsPinningToContentViewport:]: unrecognized selector sent to instance 0x102811400

**Comment by yuyunzhang** [comment]
同时使用了 IQKeyboardManager 库

**Comment by SmileZXLee** [comment]
`ZXEmptyView`中未使用到UITextField，因此这个应该不是`ZXEmptyView`导致的崩溃。
